apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-testuser
  namespace: argo-workflows
rules:
- apiGroups:
    - argoproj.io
    - ""
  resources:
    - cronworkflows
    - eventsources
    - sensors
    - workflows
    - workfloweventbindings
    - workflowtemplates
    - workflowtaskresults
    - pods
    - secrets
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
