apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-argo
  namespace: default
  labels:
    example: "true"
spec:
  serviceAccountName: argo-workflow-testuser
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: "Hello Argo!"
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - "Hello Argo!"
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
