apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo-workflows
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      endpoint: argo-artifacts.argo-workflows.svc.cluster.local:9000
      bucket: argo-artifacts
      insecure: true
      accessKeySecret:
        name: argo-artifacts
        key: rootUser
      secretKeySecret:
        name: argo-artifacts
        key: rootPassword
