apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: kafka-confluent-poc-dev
  destination:
    #server: https://kubernetes.default.svc
    namespace: argoworky
    name: in-cluster
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.47.0
    helm:
      values: |
        crds:
          full: true
