apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: kafka-poc
  namespace: default
spec:
  archiveLogs: true
  artifactRepositoryRef:
    configMap: workflow-controller-configmap
    key: artifactRepository
  serviceAccountName: argo-workflow-testuser
  entrypoint: list-topics
  templates:
    - name: list-topics
      container:
        name: main
        image: confluentinc/cp-server:7.5.0
        command: ["/bin/bash"]
        args: ["-c", 'cd / && ./tmp/list-topics.sh']
        volumeMounts:
          - mountPath: "/mnt"
            name: kafka-poc-user-properties
          - mountPath: "/tmp"
            name: kafka-poc-commands
      volumes:
        - name: kafka-poc-user-properties
          secret:
            secretName: kafka-poc-user-properties
        - name: kafka-poc-commands
          configMap:
            name: kafka-poc-commands
            defaultMode: 0755
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
---
kind: Secret
apiVersion: v1
metadata:
  name: kafka-poc-user-properties
  namespace: default
data:
  kafka_user.properties: c2FzbC5qYWFzLmNvbmZpZz1vcmcuYXBhY2hlLmthZmthLmNvbW1vbi5zZWN1cml0eS5wbGFpbi5QbGFpbkxvZ2luTW9kdWxlIHJlcXVpcmVkIHVzZXJuYW1lPSJrYWZrYSIgcGFzc3dvcmQ9ImthZmthIjsKc2FzbC5tZWNoYW5pc209UExBSU4Kc2VjdXJpdHkucHJvdG9jb2w9U0FTTF9QTEFJTlRFWFQ=
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-poc-commands
  namespace: default
data:
  list-topics.sh: >-
    #!/bin/bash 

    cd /bin

    echo 'list topics:'

    kafka-topics --list --bootstrap-server kafka.kafka-confluent-poc.svc.cluster.local:9092 --command-config /mnt/kafka_user.properties