apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cfk-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AndreasWeichselbaum/cfk-demo-helm-chart'
    path: cfk-demo
    targetRevision: v0.1.1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cfk

