apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cfk-demo-dev
  namespace: argocd
spec:
  project: kafka-confluent-poc-dev
  source:
    repoURL: 'https://github.com/AndreasWeichselbaum/cfk-demo-helm-chart'
    path: cfk-demo
    targetRevision: main
    helm:
      valuesObject:
        kafka:
          replicas: 3
  destination:
    name: in-cluster
    namespace: kafka-confluent-poc
