apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cfk-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AndreasWeichselbaum/cfk-demo-helm-chart'
    path: cfk-demo
    targetRevision: v0.2.0
    helm:
      valuesObject:
        kafka:
          replicas: 3
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka-confluent-demo
